# Generated by Django 4.2.7 on 2023-12-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('pic', models.FilePathField()),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=255)),
                ('pubdate', models.DateTimeField()),
                ('dist_date', models.DateField()),
            ],
        ),
    ]
