# Generated by Django 4.2.7 on 2023-12-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescreen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pic',
            field=models.TextField(),
        ),
    ]
